### ISSUE TITLE
Talk slides URLs tracking

### ISSUE THREAD

**Issue by ndenny** [pycascades/welcome-wagon-2019#40]
- [x] - Katie McLaughlin: Turning 'wat' into 'why'
- [x] - Al Sweigart: The Amazing Mutable, Immutable Tuple 
- [x] - Jigyasa Grover: Perceiving Python Programming Paradigms 
- [ ] - Josh Weissbock: Distributed Web Scraping in Python
- [x] - Iyanuoluwa Ajao: Type Hints: Adding Types to Legacy Code 
- [x] - Maria McKinley: Hunting the bugs
- [x] - Norah Klintberg Sakal: Guide to your own artificial intelligence application in 3 easy steps 
- [ ] - Ania Kapuścińska: Lint your code responsibly! 
- [x] - Chirag Shah: Understanding Multithreading 
- [x] - Ben Berry: Who to blame for all your problems 
- [x] - Hayley Denbraver: Recursion, Fractals, and the Python Turtle Module

- [x] - Nina Zakharenko: Light Up Your Life - With Python and LEDs! 
- [ ] - Dustin Ingram: Data Protection for Developers: Past, Present, and Future 
- [x] - Omayeli Arenyeka: Building a Gendered Dictionary 
- [x] - Andy Fundinger: A Taxonomy of Decorators: A-E 
- [x] - Paul Watts: Given this, assert that: fluent testing using fixtures and properties 
- [x] - Kyungyun Lee: So tell me, what is your musical taste? 
- [x] - Chris Waigl: Abstraction for students of all the things 
- [x] - Abhishek Kapatkar: Nim for Python Programmers
- [ ] - Philip James and Asheesh Laroia: Account Security for the Fashionable App Developer
- [x] - Trey Hunner: Meaningful Mentoring Moments

**Comment by abeyer** [comment]
Also, Lightning Talks:

- [x] Michael Gat: https://docs.google.com/presentation/d/e/2PACX-1vTANtWQr17RF-fxFz_jpZP-M4RXOZVQJ3BODbWAfHkGyG6HauMKEbRDKxvU5wvrqmgG83J8dUwxyLUm/pub?start=false&loop=false&delayms=30000&slide=id.p
- [x] Derek Ardolf: https://docs.google.com/presentation/d/e/2PACX-1vTANtWQr17RF-fxFz_jpZP-M4RXOZVQJ3BODbWAfHkGyG6HauMKEbRDKxvU5wvrqmgG83J8dUwxyLUm/pub?start=false&loop=false&delayms=30000&slide=id.p
- [x] Aly Sivji: http://bit.ly/busy-beaver-lightning
- [x] Hanna Landrus: https://docs.google.com/presentation/d/1KE-XzWBbkZrbtsXTR95ErutFgMDaJwLLcTxVDIbYToU/edit?usp=sharing
- [x] @RollerAngel: https://docs.google.com/document/d/1qTp7JUkYf0dqKtgA1FTM-gq0HSVqr8FtJZJfM9N-DDM/edit?usp=sharing
- [x] Veronica Hanus: https://docs.google.com/presentation/d/1wRL3FaC82hcaeX95rtWQ-K5J_Lag7QY842tngJ9pWp0/edit?usp=drivesdk

**Comment by ndenny** [comment]
Lightning Day 2:

- [x] Mariatta: https://docs.google.com/presentation/d/1yvJKTGbbYCpMQ_CuZ-Vfvc_SiyuYmshLZwk8Q3FJ-xk/edit?usp=sharing
- [x] Jason Wattier: https://docs.google.com/presentation/d/10hlAzyj4qEcfb8uPWacHatB1VgXszRGJoum3HDPU_LM/edit?usp=sharing
- [x] Nick Ballenger: https://docs.google.com/presentation/d/1px1QW6NkLDeiBKYHA5Ccwwtxfd9W9fvAogck431d1p0
- [x] Alex LordThorsen: https://gist.github.com/rawrgulmuffins/e34f180bd3f57a20f643196559b1faf9 
- [x] Casey Faist -

**Comment by chryss** [comment]
I just cleaned up mine a little bit, so just to check I've not broken your links:

- GitHub repo is here: https://github.com/chryss/abstraction-for-students-of-all-the-things 
- PDF can be downloaded here: https://github.com/chryss/abstraction-for-students-of-all-the-things/blob/master/cw_presentation.pdf  
- Hosted GitHub Pages HTML: https://chryss.github.io/abstraction-for-students-of-all-the-things

**Comment by ndenny** [comment]
Thank you @chryss!
